runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: "2.5.1"
- name: ssl
  version: latest

handlers:
- url: /command
  script: clock.app
- url: /update
  script: clock.app
  login: admin
